### ISSUE TITLE
Disseny de la Pàgina d'Administració

### ISSUE THREAD

**Issue by juanjogomezvillegas** [Projecte4-Webs-al-punt/Projecte4-Gestor-de-Torns-Professors#13]
[https://github.com/Projecte4-Webs-al-punt/Projecte4-Gestor-de-Torns-Professors/tree/feature-dashboard](https://github.com/Projecte4-Webs-al-punt/Projecte4-Gestor-de-Torns-Professors/tree/feature-dashboard)

**Comment by m04a** [comment]
Disseny acabat només falta implementar algunes tocs finals
