### ISSUE TITLE
Implementar la resposta del professor

### ISSUE THREAD

**Issue by juanjogomezvillegas** [Projecte4-Webs-al-punt/Projecte4-Gestor-de-Torns-Professors#21]
El Moha li fa molta il·lusió fer un modal per preguntar dubtes. Potser tindrà un dubte que preguntar?

**Comment by juanjogomezvillegas** [comment]
falta temps

**Comment by m04a** [comment]
Nono tinc pensat fer-ho dema

**Comment by m04a** [comment]
Fet xD por misss weboosss
