### ISSUE TITLE
TRAGEDIA!!! El Generador de Alumnes no Funciona

### ISSUE THREAD

**Issue by juanjogomezvillegas** [Projecte4-Webs-al-punt/Projecte4-Gestor-de-Torns-Professors#40]

**Comment by juanjogomezvillegas** [comment]
Crec que ja funciona

**Comment by juanjogomezvillegas** [comment]
Espero que a la presentació vagui bé

**Comment by m04a** [comment]
Bueno en teoria ja funciona, ho passo a producció en uns minuts. Com ho vaig fer jo lo de la API en la main per lo dels canvis que es van perdre s'ha liat una mica però ja funciona
